"""Generate the container's Dagster instance config before Dagster starts."""

from __future__ import annotations

import json
import os
import re
import sys
from collections.abc import MutableMapping
from pathlib import Path
from urllib.parse import parse_qsl, quote, urlencode, urlsplit, urlunsplit

DEFAULT_SCHEMA = "dagster"
DEFAULT_DATABASE = "urban_rag"
DEFAULT_USER = "urban_rag"
DEFAULT_PORT = "5432"
MANAGED_HEADER = (
    "# Generated by urban_rag.dagster_home. Configure with DAGSTER_* or "
    "URBAN_RAG_PG_* environment variables.\n"
)
_VALID_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    configure_dagster_home(Path(os.environ.get("DAGSTER_HOME", "/dagster_home")))
    if not args:
        return 0
    os.execvp(args[0], args)
    return 127


def configure_dagster_home(
    home: Path, env: MutableMapping[str, str] = os.environ
) -> Path:
    """Write ``dagster.yaml`` and return its path.

    With no Postgres settings, Dagster keeps its default local instance storage.
    When a Postgres URL or host is present, the generated config points Dagster's
    run/event/schedule storage at that database and sets ``search_path`` to the
    dedicated Dagster schema.
    """

    url = postgres_url_from_env(env)
    path = home / "dagster.yaml"
    if url:
        env["DAGSTER_POSTGRES_URL"] = url
        _write_config(path, _postgres_config(), force=True)
    else:
        _write_config(path, _local_config(), force=False)
    return path


def postgres_url_from_env(env: MutableMapping[str, str]) -> str | None:
    schema = _schema(env)
    explicit = _first(
        env, "DAGSTER_POSTGRES_URL", "DAGSTER_PG_DSN", "URBAN_RAG_PG_DSN"
    )
    if explicit:
        return _with_search_path(explicit, schema, env)

    host = _first(env, "DAGSTER_PG_HOST", "DAGSTER_PG_HOSTNAME", "URBAN_RAG_PG_HOST")
    if not host:
        return None

    user = _first(env, "DAGSTER_PG_USER", "DAGSTER_PG_USERNAME", "URBAN_RAG_PG_USER")
    database = _first(
        env, "DAGSTER_PG_DATABASE", "DAGSTER_PG_DB", "URBAN_RAG_PG_DATABASE"
    )
    port = _first(env, "DAGSTER_PG_PORT", "URBAN_RAG_PG_PORT") or DEFAULT_PORT
    password = _first(env, "DAGSTER_PG_PASSWORD", "URBAN_RAG_PG_PASSWORD", "PGPASSWORD")
    secret_id = _first(env, "DAGSTER_PG_SECRET_ID", "URBAN_RAG_PG_SECRET_ID")

    if secret_id and not password:
        secret = _load_secret(secret_id, env)
        user = str(secret.get("username") or user or DEFAULT_USER)
        password = str(secret["password"])
        host = str(secret.get("host") or host)
        port = str(secret.get("port") or port)
        database = str(
            secret.get("dbname")
            or secret.get("database")
            or database
            or DEFAULT_DATABASE
        )

    if not password:
        if _flag(_first(env, "DAGSTER_PG_IAM_AUTH", "URBAN_RAG_PG_IAM_AUTH")):
            raise SystemExit(
                "Dagster Postgres storage needs a durable password, secret, or "
                "DAGSTER_POSTGRES_URL. RDS IAM tokens expire too quickly for "
                "Dagster's long-lived instance storage connections."
            )
        raise SystemExit(
            "Postgres Dagster storage was requested, but no password was set. "
            "Set DAGSTER_PG_PASSWORD, DAGSTER_PG_SECRET_ID, "
            "URBAN_RAG_PG_PASSWORD, or URBAN_RAG_PG_SECRET_ID."
        )

    if not port.isdigit():
        raise SystemExit(f"Postgres port must be numeric, got {port!r}.")

    query = {
        "application_name": "dagster",
        "options": f"-csearch_path={schema},public",
        "sslmode": _first(env, "DAGSTER_PG_SSLMODE", "URBAN_RAG_PG_SSLMODE")
        or "verify-full",
    }
    sslrootcert = _first(
        env, "DAGSTER_PG_SSLROOTCERT", "URBAN_RAG_PG_SSLROOTCERT", "PGSSLROOTCERT"
    )
    if sslrootcert:
        query["sslrootcert"] = sslrootcert

    netloc = (
        f"{quote(user or DEFAULT_USER, safe='')}:{quote(password, safe='')}"
        f"@{host}:{port}"
    )
    return urlunsplit(
        (
            "postgresql",
            netloc,
            "/" + quote(database or DEFAULT_DATABASE, safe=""),
            urlencode(query),
            "",
        )
    )


def _with_search_path(url: str, schema: str, env: MutableMapping[str, str]) -> str:
    parts = urlsplit(url)
    query = dict(parse_qsl(parts.query, keep_blank_values=True))
    query.setdefault("application_name", "dagster")
    query.setdefault("options", f"-csearch_path={schema},public")
    sslmode = _first(env, "DAGSTER_PG_SSLMODE", "URBAN_RAG_PG_SSLMODE")
    if sslmode:
        query.setdefault("sslmode", sslmode)
    sslrootcert = _first(
        env, "DAGSTER_PG_SSLROOTCERT", "URBAN_RAG_PG_SSLROOTCERT", "PGSSLROOTCERT"
    )
    if sslrootcert:
        query.setdefault("sslrootcert", sslrootcert)
    return urlunsplit(
        (
            parts.scheme or "postgresql",
            parts.netloc,
            parts.path,
            urlencode(query),
            parts.fragment,
        )
    )


def _load_secret(secret_id: str, env: MutableMapping[str, str]) -> dict[str, object]:
    region = _first(
        env, "DAGSTER_PG_REGION", "URBAN_RAG_PG_REGION", "AWS_REGION", "AWS_DEFAULT_REGION"
    )
    profile = _first(env, "AWS_PROFILE")
    try:
        import boto3
        from botocore.exceptions import ProfileNotFound

        try:
            session = (
                boto3.Session(profile_name=profile, region_name=region)
                if profile
                else boto3.Session(region_name=region)
            )
        except ProfileNotFound:
            session = boto3.Session(region_name=region)
        payload = session.client("secretsmanager").get_secret_value(
            SecretId=secret_id
        )["SecretString"]
        secret = json.loads(payload)
    except Exception as exc:  # pragma: no cover - depends on live AWS credentials
        raise SystemExit(
            f"Could not read Dagster Postgres secret {secret_id!r}: {exc}"
        ) from exc
    if "password" not in secret:
        raise SystemExit(f"Dagster Postgres secret {secret_id!r} has no password field.")
    return secret


def _schema(env: MutableMapping[str, str]) -> str:
    schema = _first(env, "DAGSTER_POSTGRES_SCHEMA") or DEFAULT_SCHEMA
    if not _VALID_IDENTIFIER.match(schema):
        raise SystemExit(
            f"DAGSTER_POSTGRES_SCHEMA={schema!r} is not a valid SQL identifier."
        )
    return schema


def _write_config(path: Path, text: str, *, force: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if current == text:
            return
        if not force and current.strip() and not current.startswith(MANAGED_HEADER):
            return
    path.write_text(text, encoding="utf-8")


def _local_config() -> str:
    return MANAGED_HEADER + "telemetry:\n  enabled: false\n"


def _postgres_config() -> str:
    return (
        MANAGED_HEADER
        + "telemetry:\n"
        + "  enabled: false\n"
        + "storage:\n"
        + "  postgres:\n"
        + "    postgres_url:\n"
        + "      env: DAGSTER_POSTGRES_URL\n"
    )


def _first(env: MutableMapping[str, str], *names: str) -> str | None:
    for name in names:
        value = env.get(name)
        if value and value.strip():
            return value.strip()
    return None


def _flag(value: str | None) -> bool:
    return value is not None and value.strip().lower() in {"1", "true", "yes", "on"}


if __name__ == "__main__":
    raise SystemExit(main())
